### PR TITLE
Added EventManager

### PR DESCRIPTION
**Pull request by Lomadriel**
I think now Event Manager is functional. 

See #38

### CODE REVIEW

**Comment by Lomadriel** [comment]
I must add some documentation before we can merge.

**Comment by Lomadriel** [comment]
Done.

**Comment by Lomadriel** [comment]
We should also add deleteListener() and clearListener() methods.

**Comment by Lomadriel** [comment]
Done

**Comment by CBenoit** [comment]
I'm going to test the example and read all the code then confirm the merge.

**Comment by Lomadriel** [comment]
So I think we can confirm the merge ?

**Comment by CBenoit** [comment]
There is still this issue : https://github.com/Mirai-Team/mirai-project/issues/38#issuecomment-76596282
And by the way, it seems that you "only" did a communication system (broadcast), not really an event manager. Or at least, it's not what I think it would be. Let me some time to think about it.

**Comment by Lomadriel** [comment]
CBenoit:

> And by the way, it seems that you "only" did a communication system (broadcast), not really an event manager. Or at least, it's not what I think it would be. Let me some time to think about it.

Yes, it's more a broadcasting system than an event manager.

For the warning, I don't know how to correct it properly.

**Comment by Lomadriel** [comment]
I have find a way but I need some time to finish it.

**Comment by Lomadriel** [comment]
Warning corrected.

**Comment by Lomadriel** [comment]
Exemple improved.

**Pull request merged**
